version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean package -Dmaven.test.skip=true
artifacts:
  files:
    - target/Authorization-0.0.1-SNAPSHOT.jar
  discard-paths: yes
